### ISSUE TITLE
Add support for kubefleet clusterresourceplacement manifests

### ISSUE THREAD

**Issue by sjwaight** [sjwaight/draft#1]
I'd like Draft to support Kubefleet's cluster resource placement manifest generation. The following two clusterresourceplacement manifests should be supported. The code should allow you to set values for:

metadata.name
spec.resourceSelectors.name
policy.placementType

```yaml
apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: demo-crp
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: fmad-demo
      version: v1
  policy:
    placementType: PickAll
```

For the second sample, the code should allow you to additionally set the clusterNames array.

```yaml
apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: fmad-demo-crp
spec:
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: fmad-demo
      version: v1
  policy:
    placementType: PickFixed
    clusterNames:
       - cluster-name-01
       - cluster-name-02
```
